services:
  - type: web
    name: mdshare
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
